name: VitalHome
version: @version@
main: dev.meinel.leo.vitalhome.VitalHome
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives players the ability to set homes and teleport to them.
commands:
  home:
    description: "Main command"
    usage: "/home <name>"
  sethome:
    description: "Main command"
    usage: "/sethome <name>"
  delhome:
    description: "Main command"
    usage: "/delhome <name>"
  homes:
    description: "Main command"
    usage: "/homes"
permissions:
  vitalhome.home:
    description: "Permission to teleport home"
    default: op
  vitalhome.sethome:
    description: "Permission to set a home"
    default: op
  vitalhome.delhome:
    description: "Permission to delete a home"
    default: op
  vitalhome.list:
    description: "Permission to list homes"
    default: op
  vitalhome.homes:
    description: "Permission with number of homes a player can set (fex. vitalhome.homes.2 = 2 homes)"
    default: op
  vitalhome.delay.bypass:
    description: "Permission to bypass delay"
    default: op